# Generated by Django 4.1 on 2022-09-02 22:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bill_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_status', models.CharField(max_length=55)),
                ('count', models.IntegerField(default=1)),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('card_board', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('university_number', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('batch', models.IntegerField()),
                ('level', models.CharField(max_length=255)),
                ('stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.language')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=2000)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.bill')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetype')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.level')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.student')),
            ],
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.student'),
        ),
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_board', models.BooleanField(default=False)),
                ('colored', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.level')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificaterequest')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificaterequest'),
        ),
    ]
