# Generated by Django 4.1 on 2022-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='request_status',
            field=models.CharField(choices=[('wfp', 'waiting for payment'), ('ip', 'in_process'), ('rd', 'ready'), ('rcv', 'received')], default=('wfp', 'waiting for payment'), max_length=55),
        ),
    ]
