# Generated by Django 4.1 on 2022-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificaterequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('DIP', 'دبلوم'), ('HD', 'دبلوم عالي'), ('BCH', 'بكلاريوس'), ('M', 'ماجستير'), ('PHD', 'دكتوراة')], max_length=255),
        ),
    ]
