# Generated by Django 4.1 on 2022-09-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_level_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
        migrations.AddField(
            model_name='student',
            name='last_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='certificateitem',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.certificatetype'),
        ),
        migrations.AlterField(
            model_name='certificateitem',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.language'),
        ),
        migrations.AlterField(
            model_name='certificateitem',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.level'),
        ),
        migrations.AlterField(
            model_name='leveltypelink',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.certificatetype'),
        ),
        migrations.AlterField(
            model_name='leveltypelink',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='certificates.level'),
        ),
    ]
