# Generated by Django 4.1 on 2022-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_remove_student_level_student_last_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uni_num',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_number',
            field=models.CharField(default=models.CharField(max_length=25, null=True, unique=True), editable=False, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
