# Generated by Django 4.1 on 2022-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_student_uni_num_alter_student_university_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uni_num',
        ),
        migrations.AlterField(
            model_name='student',
            name='university_number',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
