# Generated by Django 4.1 on 2022-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificaterequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateitem',
            name='status',
            field=models.CharField(choices=[('wfp', 'waiting for payment'), ('ip', 'in_process'), ('rd', 'ready'), ('rcv', 'received')], default=('wfp', 'waiting for payment'), max_length=55),
        ),
    ]
