# Generated by Django 4.1 on 2022-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_certificateitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificateitem',
            name='colored',
            field=models.BooleanField(default=False),
        ),
    ]
