# Generated by Django 4.1 on 2022-09-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_bill_expiry_date_alter_certificateitem_colored'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='certificates.student'),
        ),
    ]
